package jsdiff_test

import (
	"fmt"
	"os"
	"regexp"
	"strings"
	"testing"

	"github.com/keejkrej/pi-go/internal/jsdiff"
	"github.com/keejkrej/pi-go/internal/jsonx"
)

// The vectors are generated by running diff@8.0.4 under node (see the generator field).
type vecFile struct {
	Generator string              `json:"generator"`
	Segments  map[string][]string `json:"segments"`
	Cases     []vecCase           `json:"cases"`
}

type vecOpts struct {
	IgnoreWhitespace       *bool    `json:"ignoreWhitespace"`
	NewlineIsToken         bool     `json:"newlineIsToken"`
	StripTrailingCr        bool     `json:"stripTrailingCr"`
	IgnoreNewlineAtEof     bool     `json:"ignoreNewlineAtEof"`
	IgnoreCase             bool     `json:"ignoreCase"`
	OneChangePerToken      bool     `json:"oneChangePerToken"`
	MaxEditLength          *int     `json:"maxEditLength"`
	Timeout                *float64 `json:"timeout"`
	Comparator             string   `json:"comparator"`
	StringifyReplacer      string   `json:"stringifyReplacer"`
	IntlSegmenter          bool     `json:"intlSegmenter"`
	Context                *int     `json:"context"`
	HeaderOptions          string   `json:"headerOptions"`
	FuzzFactor             int      `json:"fuzzFactor"`
	AutoConvertLineEndings *bool    `json:"autoConvertLineEndings"`
	CompareLine            string   `json:"compareLine"`
}

type vecCase struct {
	Fn        string   `json:"fn"`
	A         string   `json:"a"`
	B         string   `json:"b"`
	JA        any      `json:"ja"`
	JB        any      `json:"jb"`
	Opts      *vecOpts `json:"opts"`
	OldName   string   `json:"oldName"`
	NewName   string   `json:"newName"`
	OldHeader *string  `json:"oldHeader"`
	NewHeader *string  `json:"newHeader"`
	Patch     string   `json:"patch"`
	Result    any      `json:"result"`
	Error     *string  `json:"error"`
}

// replaySegmenter replays the Intl.Segmenter('en', {granularity: 'word'}) segmentations
// recorded by the generator.
type replaySegmenter struct {
	t        *testing.T
	segments map[string][]string
}

func (s replaySegmenter) Granularity() string { return "word" }

func (s replaySegmenter) Segment(str string) []string {
	segs, ok := s.segments[str]
	if !ok {
		s.t.Fatalf("no recorded segmentation for %q", str)
	}
	return segs
}

var wsRun = regexp.MustCompile(`\s+`)

func diffOptions(t *testing.T, o *vecOpts, segments map[string][]string) *jsdiff.Options {
	if o == nil {
		return nil
	}
	opts := &jsdiff.Options{
		IgnoreWhitespace:   o.IgnoreWhitespace,
		NewlineIsToken:     o.NewlineIsToken,
		StripTrailingCr:    o.StripTrailingCr,
		IgnoreNewlineAtEof: o.IgnoreNewlineAtEof,
		IgnoreCase:         o.IgnoreCase,
		OneChangePerToken:  o.OneChangePerToken,
		MaxEditLength:      o.MaxEditLength,
	}
	if o.Timeout != nil {
		ms := int64(*o.Timeout)
		opts.Timeout = &ms
	}
	switch o.Comparator {
	case "":
	case "trimEq":
		// (l, r) => l.trim() === r.trim()
		opts.Comparator = func(l, r string) bool { return jsTrimForTest(l) == jsTrimForTest(r) }
	default:
		t.Fatalf("unknown comparator %q", o.Comparator)
	}
	switch o.StringifyReplacer {
	case "":
	case "dropSecret":
		opts.StringifyReplacer = func(key string, v any) (any, bool) {
			if key == "secret" {
				return nil, false
			}
			return v, true
		}
	case "upperStrings":
		opts.StringifyReplacer = func(_ string, v any) (any, bool) {
			if s, ok := v.(string); ok {
				return strings.ToUpper(s), true
			}
			return v, true
		}
	default:
		t.Fatalf("unknown replacer %q", o.StringifyReplacer)
	}
	if o.IntlSegmenter {
		opts.IntlSegmenter = replaySegmenter{t: t, segments: segments}
	}
	return opts
}

// jsTrimForTest is String.prototype.trim (ECMAScript WhiteSpace and LineTerminator).
func jsTrimForTest(s string) string {
	return strings.Trim(s, " \t\n\v\f\r\u00a0\u1680\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u2028\u2029\u202f\u205f\u3000\ufeff")
}

func headerOptions(t *testing.T, name string) *jsdiff.HeaderOptions {
	switch name {
	case "":
		return nil
	case "INCLUDE_HEADERS":
		return &jsdiff.IncludeHeaders
	case "FILE_HEADERS_ONLY":
		return &jsdiff.FileHeadersOnly
	case "OMIT_HEADERS":
		return &jsdiff.OmitHeaders
	}
	t.Fatalf("unknown header options %q", name)
	return nil
}

func patchOptions(t *testing.T, o *vecOpts, segments map[string][]string) *jsdiff.PatchOptions {
	if o == nil {
		return nil
	}
	return &jsdiff.PatchOptions{
		Options:       *diffOptions(t, o, segments),
		Context:       o.Context,
		HeaderOptions: headerOptions(t, o.HeaderOptions),
	}
}

func applyOptions(t *testing.T, o *vecOpts) *jsdiff.ApplyPatchOptions {
	if o == nil {
		return nil
	}
	opts := &jsdiff.ApplyPatchOptions{FuzzFactor: o.FuzzFactor, AutoConvertLineEndings: o.AutoConvertLineEndings}
	switch o.CompareLine {
	case "":
	case "ignoreWs":
		opts.CompareLine = func(_ int, line *string, _ string, content string) bool {
			return line != nil && wsRun.ReplaceAllString(*line, "") == wsRun.ReplaceAllString(content, "")
		}
	default:
		t.Fatalf("unknown compareLine %q", o.CompareLine)
	}
	return opts
}

func changesValue(changes []jsdiff.Change) any {
	if changes == nil {
		return nil
	}
	return changes
}

func applyValue(result string, ok bool) any {
	if !ok {
		return false
	}
	return result
}

// normPatch renders a parsed patch in the generator's normalized key order.
func normPatch(p *jsdiff.StructuredPatch) *jsonx.Object {
	opt := func(s *string) any {
		if s == nil {
			return nil
		}
		return *s
	}
	hunks := make([]any, len(p.Hunks))
	for i, h := range p.Hunks {
		lines := make([]any, len(h.Lines))
		for k, l := range h.Lines {
			lines[k] = l
		}
		hunks[i] = jsonx.ObjectOf(
			"oldStart", float64(h.OldStart), "oldLines", float64(h.OldLines),
			"newStart", float64(h.NewStart), "newLines", float64(h.NewLines), "lines", lines,
		)
	}
	return jsonx.ObjectOf(
		"index", opt(p.Index), "oldFileName", p.OldFileName, "oldHeader", opt(p.OldHeader),
		"newFileName", p.NewFileName, "newHeader", opt(p.NewHeader), "hunks", hunks,
	)
}

// runCase computes the Go result of one vector; err is a returned error (TS: thrown).
func runCase(t *testing.T, c *vecCase, segments map[string][]string) (result any, err error) {
	defer func() {
		// A few TS throws are Go panics (misuse of the API, see the package doc).
		if r := recover(); r != nil {
			err = fmt.Errorf("%v", r)
		}
	}()
	switch c.Fn {
	case "diffLines":
		return changesValue(jsdiff.DiffLines(c.A, c.B, diffOptions(t, c.Opts, segments))), nil
	case "diffTrimmedLines":
		return changesValue(jsdiff.DiffTrimmedLines(c.A, c.B, diffOptions(t, c.Opts, segments))), nil
	case "diffWords":
		return changesValue(jsdiff.DiffWords(c.A, c.B, diffOptions(t, c.Opts, segments))), nil
	case "diffWordsWithSpace":
		return changesValue(jsdiff.DiffWordsWithSpace(c.A, c.B, diffOptions(t, c.Opts, segments))), nil
	case "diffChars":
		return changesValue(jsdiff.DiffChars(c.A, c.B, diffOptions(t, c.Opts, segments))), nil
	case "diffSentences":
		return changesValue(jsdiff.DiffSentences(c.A, c.B, diffOptions(t, c.Opts, segments))), nil
	case "diffCss":
		return changesValue(jsdiff.DiffCss(c.A, c.B, diffOptions(t, c.Opts, segments))), nil
	case "diffArrays":
		var opts *jsdiff.ArrayOptions[any]
		if c.Opts != nil {
			opts = &jsdiff.ArrayOptions[any]{OneChangePerToken: c.Opts.OneChangePerToken, MaxEditLength: c.Opts.MaxEditLength}
		}
		changes := jsdiff.DiffArrays(c.JA.([]any), c.JB.([]any), opts)
		if changes == nil {
			return nil, nil
		}
		return changes, nil
	case "diffJson":
		changes, err := jsdiff.DiffJson(c.JA, c.JB, diffOptions(t, c.Opts, segments))
		return changesValue(changes), err
	case "canonicalize":
		return jsdiff.Canonicalize(c.JA, nil)
	case "createTwoFilesPatch":
		patch := jsdiff.CreateTwoFilesPatch(c.OldName, c.NewName, c.A, c.B, c.OldHeader, c.NewHeader, patchOptions(t, c.Opts, segments))
		if patch == "" {
			return nil, nil
		}
		return patch, nil
	case "createPatch":
		return jsdiff.CreatePatch(c.OldName, c.A, c.B, c.OldHeader, c.NewHeader, patchOptions(t, c.Opts, segments)), nil
	case "structuredPatch":
		patch := jsdiff.NewStructuredPatch(c.OldName, c.NewName, c.A, c.B, c.OldHeader, c.NewHeader, patchOptions(t, c.Opts, segments))
		if patch == nil {
			return nil, nil
		}
		return patch, nil
	case "parsePatch":
		patches, err := jsdiff.ParsePatch(c.Patch)
		if err != nil {
			return nil, err
		}
		out := make([]any, len(patches))
		for i, p := range patches {
			out[i] = normPatch(p)
		}
		return out, nil
	case "formatPatch":
		patches, err := jsdiff.ParsePatch(c.Patch)
		if err != nil {
			return nil, err
		}
		var ho *jsdiff.HeaderOptions
		if c.Opts != nil {
			ho = headerOptions(t, c.Opts.HeaderOptions)
		}
		return jsdiff.FormatPatchList(patches, ho)
	case "reversePatch":
		patches, err := jsdiff.ParsePatch(c.Patch)
		if err != nil {
			return nil, err
		}
		return jsdiff.FormatPatchList(jsdiff.ReversePatchList(patches), nil)
	case "applyPatch":
		result, ok, err := jsdiff.ApplyPatch(c.A, c.Patch, applyOptions(t, c.Opts))
		return applyValue(result, ok), err
	case "applyReversePatch":
		patches, err := jsdiff.ParsePatch(c.Patch)
		if err != nil {
			return nil, err
		}
		result, ok, err := jsdiff.ApplyPatchList(c.A, jsdiff.ReversePatchList(patches), nil)
		return applyValue(result, ok), err
	case "convertChangesToXML":
		return jsdiff.ConvertChangesToXML(jsdiff.DiffWords(c.A, c.B, nil)), nil
	case "convertChangesToDMP":
		return jsdiff.ConvertChangesToDMP(jsdiff.DiffWords(c.A, c.B, nil)), nil
	}
	t.Fatalf("unknown fn %q", c.Fn)
	return nil, nil
}

func loadVectors(t *testing.T, path string) *vecFile {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	var vf vecFile
	if err := jsonx.Unmarshal(data, &vf); err != nil {
		t.Fatal(err)
	}
	if len(vf.Cases) == 0 {
		t.Fatal("no vectors")
	}
	return &vf
}

func TestJsdiff_Vectors(t *testing.T) {
	checkVectors(t, loadVectors(t, "testdata/vectors.json"))
}

// TestJsdiff_ExtraVectors checks larger differential runs produced locally with
// `node testdata/gen.cjs <out.json> <scale> <seed>`; JSDIFF_EXTRA_VECTORS is a
// comma-separated list of such files. Skipped when unset.
func TestJsdiff_ExtraVectors(t *testing.T) {
	paths := os.Getenv("JSDIFF_EXTRA_VECTORS")
	if paths == "" {
		t.Skip("JSDIFF_EXTRA_VECTORS not set")
	}
	for _, p := range strings.Split(paths, ",") {
		t.Run(p, func(t *testing.T) { checkVectors(t, loadVectors(t, p)) })
	}
}

func checkVectors(t *testing.T, vf *vecFile) {
	counts := map[string]int{}
	nonNull := 0
	defer func() {
		// Guard against a decoding regression that would turn every expectation into null.
		if nonNull < len(vf.Cases)/2 {
			t.Errorf("only %d of %d vectors have a non-null result", nonNull, len(vf.Cases))
		}
	}()
	for i := range vf.Cases {
		c := &vf.Cases[i]
		counts[c.Fn]++
		desc := func() string {
			opts, _ := jsonx.Stringify(c.Opts)
			return fmt.Sprintf("case %d %s a=%q b=%q ja=%v jb=%v patch=%q opts=%s", i, c.Fn, c.A, c.B, c.JA, c.JB, c.Patch, opts)
		}
		got, err := runCase(t, c, vf.Segments)
		if c.Error != nil {
			if err == nil {
				gotJSON, _ := jsonx.Stringify(got)
				t.Errorf("%s:\n want error %q\n got result %s", desc(), *c.Error, gotJSON)
			} else if err.Error() != *c.Error {
				t.Errorf("%s:\n want error %q\n got error  %q", desc(), *c.Error, err.Error())
			}
			continue
		}
		if err != nil {
			t.Errorf("%s: unexpected error %v", desc(), err)
			continue
		}
		gotJSON, err := jsonx.Stringify(got)
		if err != nil {
			t.Fatalf("%s: stringify: %v", desc(), err)
		}
		wantJSON, err := jsonx.Stringify(c.Result)
		if err != nil {
			t.Fatalf("%s: stringify want: %v", desc(), err)
		}
		if wantJSON != "null" {
			nonNull++
		}
		if gotJSON != wantJSON {
			t.Errorf("%s:\n want %s\n got  %s", desc(), wantJSON, gotJSON)
		}
	}
	t.Logf("%s: %v", vf.Generator, counts)
}
