package ansi

import (
	"encoding/json"
	"os"
	"reflect"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"
)

// Vectors in testdata/chalk_vectors.json were generated by running chalk@6.0.0 (node v24.21.0) over the
// chains and inputs listed in the file (generator script: gen-chalk.mjs, not kept).
type chalkVectors struct {
	Inputs []string `json:"inputs"`
	Chains []struct {
		Level   int      `json:"level"`
		Chain   []any    `json:"chain"`
		Outputs []string `json:"outputs"`
	} `json:"chains"`
	Joins []struct {
		Level int    `json:"level"`
		Root  string `json:"root"`
		Bold2 string `json:"bold2"`
		Bold3 string `json:"bold3"`
		Bold0 string `json:"bold0"`
	} `json:"joins"`
	Conversions struct {
		Rgb           [][5]int `json:"rgb"`
		Ansi256ToAnsi []int    `json:"ansi256ToAnsi"`
		Hex           [][4]any `json:"hex"`
	} `json:"conversions"`
	Styles map[string][2]string `json:"styles"`
	Codes  [][2]int             `json:"codes"`
	Names  map[string][]string  `json:"names"`
}

func loadChalkVectors(t *testing.T) *chalkVectors {
	t.Helper()
	data, err := os.ReadFile("testdata/chalk_vectors.json")
	if err != nil {
		t.Fatal(err)
	}
	var v chalkVectors
	if err := json.Unmarshal(data, &v); err != nil {
		t.Fatal(err)
	}
	return &v
}

func pascal(name string) string {
	return strings.ToUpper(name[:1]) + name[1:]
}

// applyChainStep calls the style method named by step on recv (a *Chalk or *Builder) via reflection.
func applyChainStep(t *testing.T, recv any, step any) *Builder {
	t.Helper()
	var name string
	var args []reflect.Value
	switch s := step.(type) {
	case string:
		name = s
	case []any:
		name = s[0].(string)
		for _, a := range s[1:] {
			switch av := a.(type) {
			case string:
				args = append(args, reflect.ValueOf(av))
			case float64:
				args = append(args, reflect.ValueOf(int(av)))
			}
		}
	}
	m := reflect.ValueOf(recv).MethodByName(pascal(name))
	if !m.IsValid() {
		t.Fatalf("no method %s on %T", pascal(name), recv)
	}
	return m.Call(args)[0].Interface().(*Builder)
}

func TestChalk_ChainsMatchChalk(t *testing.T) {
	v := loadChalkVectors(t)
	for _, c := range v.Chains {
		level := c.Level
		ch := NewChalk(&Options{Level: &level})
		var recv any = ch
		var b *Builder
		for _, step := range c.Chain {
			b = applyChainStep(t, recv, step)
			recv = b
		}
		for i, input := range v.Inputs {
			if got := b.Apply(input); got != c.Outputs[i] {
				t.Errorf("level %d chain %v input %q: got %q, want %q", c.Level, c.Chain, input, got, c.Outputs[i])
			}
		}
	}
}

func TestChalk_JoinMatchesChalk(t *testing.T) {
	v := loadChalkVectors(t)
	for _, j := range v.Joins {
		level := j.Level
		ch := NewChalk(&Options{Level: &level})
		if got := ch.Join("a", "b", "c"); got != j.Root {
			t.Errorf("root join level %d: %q want %q", level, got, j.Root)
		}
		if got := ch.Bold().Join("a", "b"); got != j.Bold2 {
			t.Errorf("bold join2 level %d: %q want %q", level, got, j.Bold2)
		}
		if got := ch.Bold().Join("a", "b", "c"); got != j.Bold3 {
			t.Errorf("bold join3 level %d: %q want %q", level, got, j.Bold3)
		}
		if got := ch.Bold().Join(); got != j.Bold0 {
			t.Errorf("bold join0 level %d: %q want %q", level, got, j.Bold0)
		}
	}
}

func TestChalk_ConversionsMatchAnsiStyles(t *testing.T) {
	v := loadChalkVectors(t)
	for _, row := range v.Conversions.Rgb {
		if got := RgbToAnsi256(row[0], row[1], row[2]); got != row[3] {
			t.Errorf("RgbToAnsi256(%d,%d,%d) = %d, want %d", row[0], row[1], row[2], got, row[3])
		}
		if got := RgbToAnsi(row[0], row[1], row[2]); got != row[4] {
			t.Errorf("RgbToAnsi(%d,%d,%d) = %d, want %d", row[0], row[1], row[2], got, row[4])
		}
	}
	for code, want := range v.Conversions.Ansi256ToAnsi {
		if got := Ansi256ToAnsi(code); got != want {
			t.Errorf("Ansi256ToAnsi(%d) = %d, want %d", code, got, want)
		}
	}
	for _, row := range v.Conversions.Hex {
		hex := row[0].(string)
		rgb := row[1].([]any)
		wantRgb := [3]int{int(rgb[0].(float64)), int(rgb[1].(float64)), int(rgb[2].(float64))}
		if got := HexToRgb(hex); got != wantRgb {
			t.Errorf("HexToRgb(%q) = %v, want %v", hex, got, wantRgb)
		}
		if got := HexToAnsi256(hex); got != int(row[2].(float64)) {
			t.Errorf("HexToAnsi256(%q) = %d, want %v", hex, got, row[2])
		}
		if got := HexToAnsi(hex); got != int(row[3].(float64)) {
			t.Errorf("HexToAnsi(%q) = %d, want %v", hex, got, row[3])
		}
	}
}

func TestChalk_StyleTableMatchesAnsiStyles(t *testing.T) {
	v := loadChalkVectors(t)
	if len(styleTable) != len(v.Styles) {
		t.Errorf("style count %d, want %d", len(styleTable), len(v.Styles))
	}
	for name, codes := range v.Styles {
		got, ok := Style(name)
		if !ok || got.Open != codes[0] || got.Close != codes[1] {
			t.Errorf("Style(%q) = %+v %v, want %v", name, got, ok, codes)
		}
	}
	wantCodes := map[int]int{}
	for _, kv := range v.Codes {
		wantCodes[kv[0]] = kv[1]
	}
	if diff := cmp.Diff(wantCodes, Codes); diff != "" {
		t.Errorf("Codes mismatch (-want +got):\n%s", diff)
	}
	gotNames := map[string][]string{
		"modifierNames":        ModifierNames,
		"foregroundColorNames": ForegroundColorNames,
		"backgroundColorNames": BackgroundColorNames,
		"underlineColorNames":  UnderlineColorNames,
		"colorNames":           ColorNames,
	}
	if diff := cmp.Diff(v.Names, gotNames); diff != "" {
		t.Errorf("names mismatch (-want +got):\n%s", diff)
	}
}

func TestChalk_InvalidLevelPanics(t *testing.T) {
	for _, level := range []int{-1, 4} {
		func() {
			defer func() {
				if r := recover(); r != invalidLevelMessage {
					t.Errorf("level %d: recover() = %v", level, r)
				}
			}()
			NewChalk(&Options{Level: &level})
		}()
	}
	c := NewChalk(&Options{Level: new(2)})
	func() {
		defer func() {
			if r := recover(); r != invalidLevelMessage {
				t.Errorf("SetLevel(5): recover() = %v", r)
			}
		}()
		c.SetLevel(5)
	}()
	if c.Level() != 2 {
		t.Errorf("level changed after failed SetLevel: %d", c.Level())
	}
}

func TestChalk_LevelIsReadFromGenerator(t *testing.T) {
	c := NewChalk(&Options{Level: new(0)})
	bold := c.Bold()
	if got := bold.Apply("x"); got != "x" {
		t.Fatalf("level 0: %q", got)
	}
	bold.SetLevel(1)
	if c.Level() != 1 {
		t.Fatalf("builder SetLevel did not reach generator")
	}
	if got := bold.Cyan().Apply("x"); got != "\x1b[1m\x1b[36mx\x1b[39m\x1b[22m" {
		t.Fatalf("level 1 chain: %q", got)
	}
	// Model colors resolve the escape when the chain is built.
	hex := c.Hex("#FF0000")
	c.SetLevel(3)
	if got := hex.Apply("x"); got != "\x1b[91mx\x1b[39m" {
		t.Fatalf("hex built at level 1: %q", got)
	}
	if got := c.Hex("#FF0000").Apply("x"); got != "\x1b[38;2;255;0;0mx\x1b[39m" {
		t.Fatalf("hex built at level 3: %q", got)
	}
}

func TestChalk_PackageFuncsUseDefault(t *testing.T) {
	want := Default().Bold().Apply("x")
	if got := Bold("x"); got != want {
		t.Fatalf("Bold = %q, want %q", got, want)
	}
	if got := Hex("#fff").Apply("y"); got != Default().Hex("#fff").Apply("y") {
		t.Fatalf("Hex mismatch: %q", got)
	}
	if ChalkStderr() == nil || Default() == nil {
		t.Fatal("nil default instance")
	}
}
