package ansi

import (
	"encoding/json"
	"os"
	"testing"
)

// Vectors in testdata/supports_color_vectors.json were generated by running chalk@6.0.0's vendored
// supports-color in a fresh node v24.21.0 process per case, with exactly the listed environment and argv
// (win32 cases override process.platform and os.release()). Generator script: gen-sc.mjs, not kept.
type scVectorCall struct {
	Stream  *ColorStream     `json:"stream"`
	Options *scVectorOptions `json:"options"`
}

type scVectorOptions struct {
	SniffFlags  *bool `json:"sniffFlags"`
	StreamIsTTY *bool `json:"streamIsTTY"`
}

type scVectorCase struct {
	Env      map[string]string `json:"env"`
	Argv     []string          `json:"argv"`
	Platform string            `json:"platform"`
	Release  string            `json:"release"`
	Results  []json.RawMessage `json:"results"`
}

var scVectorCalls = []scVectorCall{
	{},
	{Stream: &ColorStream{IsTTY: true}},
	{Stream: &ColorStream{IsTTY: false}},
	{Stream: &ColorStream{IsTTY: false}, Options: &scVectorOptions{SniffFlags: new(false)}},
	{Stream: &ColorStream{IsTTY: true}, Options: &scVectorOptions{SniffFlags: new(false)}},
	{Stream: &ColorStream{IsTTY: false}, Options: &scVectorOptions{StreamIsTTY: new(true)}},
	{Options: &scVectorOptions{SniffFlags: new(false)}},
}

func scSetupCase(t *testing.T, env map[string]string, argv []string, platform, release string) {
	t.Helper()
	oldArgs, oldEnv, oldPlatform, oldRelease := scArgs, scLookupEnv, scPlatform, scOSRelease
	t.Cleanup(func() {
		scArgs, scLookupEnv, scPlatform, scOSRelease = oldArgs, oldEnv, oldPlatform, oldRelease
		scFlagForceColor, scFlagForceColorInit = nil, false
	})
	scArgs = func() []string { return append([]string{"/usr/bin/node", "/tmp/script.mjs"}, argv...) }
	scLookupEnv = func(name string) (string, bool) {
		v, ok := env[name]
		return v, ok
	}
	goPlatform := platform
	if platform == "win32" {
		goPlatform = "windows"
	}
	scPlatform = func() string { return goPlatform }
	scOSRelease = func() string { return release }
	scFlagForceColor, scFlagForceColorInit = nil, false
}

func TestSupportsColor_MatchesSupportsColor(t *testing.T) {
	data, err := os.ReadFile("testdata/supports_color_vectors.json")
	if err != nil {
		t.Fatal(err)
	}
	var cases []scVectorCase
	if err := json.Unmarshal(data, &cases); err != nil {
		t.Fatal(err)
	}
	if len(cases) == 0 {
		t.Fatal("no vectors")
	}
	for _, c := range cases {
		scSetupCase(t, c.Env, c.Argv, c.Platform, c.Release)
		for i, call := range scVectorCalls {
			var opts *SupportsColorOptions
			if call.Options != nil {
				opts = &SupportsColorOptions{SniffFlags: call.Options.SniffFlags, StreamIsTTY: call.Options.StreamIsTTY}
			}
			got := CreateSupportsColor(call.Stream, opts)
			var want *ColorSupport
			if string(c.Results[i]) != "false" {
				var w struct {
					Level    int  `json:"level"`
					HasBasic bool `json:"hasBasic"`
					Has256   bool `json:"has256"`
					Has16m   bool `json:"has16m"`
				}
				if err := json.Unmarshal(c.Results[i], &w); err != nil {
					t.Fatal(err)
				}
				want = &ColorSupport{Level: w.Level, HasBasic: w.HasBasic, Has256: w.Has256, Has16m: w.Has16m}
			}
			if (got == nil) != (want == nil) || (got != nil && *got != *want) {
				t.Errorf("env %v argv %v platform %s release %q call %d: got %+v, want %s", c.Env, c.Argv, c.Platform, c.Release, i, got, c.Results[i])
			}
		}
	}
}

func TestSupportsColor_FlagForceColorPersistsAcrossCalls(t *testing.T) {
	env := map[string]string{"FORCE_COLOR": "2"}
	scSetupCase(t, env, nil, "linux", "")
	if got := CreateSupportsColor(&ColorStream{IsTTY: false}, nil); got == nil || got.Level != 2 {
		t.Fatalf("FORCE_COLOR=2: %+v", got)
	}
	// The module-level flagForceColor keeps the last FORCE_COLOR level after the variable disappears.
	delete(env, "FORCE_COLOR")
	if got := CreateSupportsColor(&ColorStream{IsTTY: false}, nil); got == nil || got.Level != 2 {
		t.Fatalf("after unset (sniffFlags): %+v", got)
	}
	if got := CreateSupportsColor(&ColorStream{IsTTY: false}, &SupportsColorOptions{SniffFlags: new(false)}); got != nil {
		t.Fatalf("after unset (no sniffFlags): %+v", got)
	}
}
