package quickjs

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"math"
	"math/big"
	"os"
	"reflect"
	"strings"
	"testing"
	"time"
	"unicode/utf8"
)

// The parity vectors in testdata/vectors.json were generated by running the
// real quickjs-wasi 3.6.2 glue under node (with TZ=UTC) through scenarios that
// the tests below replay call for call. Values are encoded the same way on
// both sides (see enc in the generator and encValue here), so a vector
// compares equal only when the Go port produced the same result.

func TestMain(m *testing.M) {
	// The vectors were generated with the host timezone pinned to UTC.
	time.Local = time.UTC
	os.Exit(m.Run())
}

type obj = map[string]any

type vectorFile struct {
	EvalCases []struct {
		Name   string          `json:"name"`
		Code   string          `json:"code"`
		Result json.RawMessage `json:"result"`
	} `json:"evalCases"`
	FlagCases []struct {
		Name   string          `json:"name"`
		Code   string          `json:"code"`
		Flags  int             `json:"flags"`
		Result json.RawMessage `json:"result"`
	} `json:"flagCases"`
	Values    []json.RawMessage          `json:"values"`
	Scenarios map[string]json.RawMessage `json:"scenarios"`
}

func loadVectors(t *testing.T) *vectorFile {
	t.Helper()
	data, err := os.ReadFile("testdata/vectors.json")
	if err != nil {
		t.Fatal(err)
	}
	var v vectorFile
	if err := json.Unmarshal(data, &v); err != nil {
		t.Fatal(err)
	}
	return &v
}

func decodeJSON(t *testing.T, raw json.RawMessage) any {
	t.Helper()
	var v any
	if err := json.Unmarshal(raw, &v); err != nil {
		t.Fatal(err)
	}
	return v
}

// normalize round-trips a Go result through JSON so it compares with decoded vectors.
func normalize(t *testing.T, v any) any {
	t.Helper()
	data, err := json.Marshal(v)
	if err != nil {
		t.Fatalf("marshal %#v: %v", v, err)
	}
	var out any
	if err := json.Unmarshal(data, &out); err != nil {
		t.Fatal(err)
	}
	return out
}

// diff reports differences between an expected vector and the Go result.
// Expected strings that carry a host (V8) stack trace match anything: host
// stacks cannot be reproduced.
func diff(path string, want, got any, out *[]string) {
	if s, ok := want.(string); ok && strings.Contains(s, "file://") {
		return
	}
	switch w := want.(type) {
	case map[string]any:
		g, ok := got.(map[string]any)
		if !ok {
			*out = append(*out, fmt.Sprintf("%s: want object %s, got %s", path, compact(want), compact(got)))
			return
		}
		for k, wv := range w {
			gv, ok := g[k]
			if !ok {
				*out = append(*out, fmt.Sprintf("%s.%s: missing (want %s)", path, k, compact(wv)))
				continue
			}
			diff(path+"."+k, wv, gv, out)
		}
		for k := range g {
			if _, ok := w[k]; !ok {
				*out = append(*out, fmt.Sprintf("%s.%s: unexpected %s", path, k, compact(g[k])))
			}
		}
	case []any:
		g, ok := got.([]any)
		if !ok || len(g) != len(w) {
			*out = append(*out, fmt.Sprintf("%s: want %s, got %s", path, compact(want), compact(got)))
			return
		}
		for i := range w {
			diff(fmt.Sprintf("%s[%d]", path, i), w[i], g[i], out)
		}
	default:
		if !reflect.DeepEqual(want, got) {
			*out = append(*out, fmt.Sprintf("%s: want %s, got %s", path, compact(want), compact(got)))
		}
	}
}

func TestVectorDiffDetectsMismatch(t *testing.T) {
	var diffs []string
	want := decodeJSON(t, json.RawMessage(`{"a":[1,2],"b":"s","stack":"at f (file:///gen.mjs:1:1)"}`))
	diff("v", want, normalize(t, obj{"a": []any{1, 3}, "c": "s", "stack": "anything"}), &diffs)
	if len(diffs) != 3 {
		t.Errorf("want 3 differences (a[1], missing b, unexpected c), got %q", diffs)
	}
}

func compact(v any) string {
	data, err := json.Marshal(v)
	if err != nil {
		return fmt.Sprintf("%#v", v)
	}
	if len(data) > 400 {
		return string(data[:400]) + "..."
	}
	return string(data)
}

func expectVector(t *testing.T, name string, raw json.RawMessage, got any) {
	t.Helper()
	var diffs []string
	diff(name, decodeJSON(t, raw), normalize(t, got), &diffs)
	for _, d := range diffs {
		t.Error(d)
	}
}

// ---- value encoding (mirrors enc in the generator) ----

func encStr(s string) any {
	if utf8.ValidString(s) {
		return s
	}
	units := []any{}
	for _, cu := range wtf8ToUTF16(s) {
		units = append(units, float64(cu))
	}
	return obj{"$": "wtf16", "v": units}
}

// wtf8ToUTF16 decodes WTF-8 into UTF-16 code units.
func wtf8ToUTF16(s string) []uint16 {
	var out []uint16
	b := []byte(s)
	for i := 0; i < len(b); {
		c := b[i]
		switch {
		case c < 0x80:
			out = append(out, uint16(c))
			i++
		case c < 0xE0:
			out = append(out, uint16(c&0x1F)<<6|uint16(b[i+1]&0x3F))
			i += 2
		case c < 0xF0:
			out = append(out, uint16(c&0x0F)<<12|uint16(b[i+1]&0x3F)<<6|uint16(b[i+2]&0x3F))
			i += 3
		default:
			cp := rune(c&0x07)<<18 | rune(b[i+1]&0x3F)<<12 | rune(b[i+2]&0x3F)<<6 | rune(b[i+3]&0x3F)
			cp -= 0x10000
			out = append(out, uint16(0xD800+(cp>>10)), uint16(0xDC00+(cp&0x3FF)))
			i += 4
		}
	}
	return out
}

func encNum(n float64) any {
	switch {
	case math.IsNaN(n):
		return obj{"$": "number", "v": "NaN"}
	case math.IsInf(n, 1):
		return obj{"$": "number", "v": "Infinity"}
	case math.IsInf(n, -1):
		return obj{"$": "number", "v": "-Infinity"}
	case n == 0 && math.Signbit(n):
		return obj{"$": "number", "v": "-0"}
	}
	return n
}

func encValue(v any, seen map[any]int) any {
	switch x := v.(type) {
	case JSUndefined:
		return obj{"$": "undefined"}
	case nil:
		return nil
	case bool:
		return x
	case float64:
		return encNum(x)
	case string:
		return encStr(x)
	case *big.Int:
		return obj{"$": "bigint", "v": x.String()}
	case GlobalSymbol:
		return obj{"$": "symbol", "v": encStr(x.Description)}
	case ArrayBuffer:
		return obj{"$": "ArrayBuffer", "v": numbers(x)}
	case []byte:
		return obj{"$": "Uint8Array", "v": numbers(x)}
	case []uint16:
		return obj{"$": "Uint16Array", "v": numbers(x)}
	case []uint32:
		return obj{"$": "Uint32Array", "v": numbers(x)}
	case []float64:
		vals := []any{}
		for _, f := range x {
			vals = append(vals, encNum(f))
		}
		return obj{"$": "Float64Array", "v": vals}
	case *HostError:
		var stack any = obj{"$": "host"}
		if x.Stack() != nil {
			stack = encStr(*x.Stack())
		}
		return obj{"$": "Error", "name": encStr(x.Name()), "message": encStr(x.Message()), "stack": stack}
	case []any:
		if len(x) == 0 {
			return obj{"$": "array", "v": []any{}}
		}
		key := &x[0]
		if id, ok := seen[key]; ok {
			return obj{"$": "ref", "id": id}
		}
		id := len(seen)
		seen[key] = id
		vals := []any{}
		for _, e := range x {
			vals = append(vals, encValue(e, seen))
		}
		return obj{"$": "array", "id": id, "v": vals}
	case *HostObject:
		if id, ok := seen[x]; ok {
			return obj{"$": "ref", "id": id}
		}
		id := len(seen)
		seen[x] = id
		entries := []any{}
		for _, k := range x.Keys() {
			val, _ := x.Get(k)
			entries = append(entries, []any{encStr(k), encValue(val, seen)})
		}
		return obj{"$": "object", "id": id, "v": entries}
	}
	return obj{"$": fmt.Sprintf("unexpected %T", v)}
}

func numbers[T uint8 | uint16 | uint32](xs []T) []any {
	out := []any{}
	for _, x := range xs {
		out = append(out, float64(x))
	}
	return out
}

func excInfo(err error) obj {
	var jsErr *JSException
	if errors.As(err, &jsErr) {
		var stack any
		if jsErr.Stack() != nil {
			stack = encStr(*jsErr.Stack())
		}
		r := obj{"kind": "JSException", "name": encStr(jsErr.Name()), "message": encStr(jsErr.Message()), "stack": stack}
		jsErr.Dispose()
		return r
	}
	var hostErr *HostError
	if errors.As(err, &hostErr) {
		return obj{"kind": hostErr.Name(), "name": hostErr.Name(), "message": encStr(hostErr.Message())}
	}
	return obj{"kind": "Error", "name": "Error", "message": encStr(err.Error())}
}

// attempt is the generator's attempt(): { ok } or { error }. A panic carrying
// an error (use after Dispose) counts as a thrown error.
func attempt(fn func() (any, error)) (result obj) {
	defer func() {
		if r := recover(); r != nil {
			err, ok := r.(error)
			if !ok {
				panic(r)
			}
			result = obj{"error": excInfo(err)}
		}
	}()
	v, err := fn()
	if err != nil {
		return obj{"error": excInfo(err)}
	}
	return obj{"ok": v}
}

func dumpEnc(vm *QuickJS, h *JSValueHandle) (any, error) {
	d, err := vm.Dump(h)
	if err != nil {
		return nil, err
	}
	return encValue(d, map[any]int{}), nil
}

func mustDumpEnc(t *testing.T, vm *QuickJS, h *JSValueHandle) any {
	t.Helper()
	v, err := dumpEnc(vm, h)
	if err != nil {
		t.Fatalf("dump: %v", err)
	}
	return v
}

func evalDumpFlags(vm *QuickJS, code, filename string, flags int) obj {
	return attempt(func() (any, error) {
		h, err := vm.EvalCode(code, filename, flags)
		if err != nil {
			return nil, err
		}
		defer h.Dispose()
		return dumpEnc(vm, h)
	})
}

func evalDump(vm *QuickJS, code string) obj {
	return evalDumpFlags(vm, code, "<eval>", 0)
}

func newVM(t *testing.T, opts *QuickJSOptions) *QuickJS {
	t.Helper()
	vm, err := QuickJSCreate(context.Background(), opts)
	if err != nil {
		t.Fatalf("create: %v", err)
	}
	return vm
}

func mustEval(t *testing.T, vm *QuickJS, code string) *JSValueHandle {
	t.Helper()
	h, err := vm.EvalCode(code, "<eval>", 0)
	if err != nil {
		t.Fatalf("eval %q: %v", code, err)
	}
	return h
}

// settledNow receives a ResolvePromise result that must already be available.
func settledNow(t *testing.T, ch <-chan PromiseResult) PromiseResult {
	t.Helper()
	select {
	case r := <-ch:
		return r
	default:
		t.Fatal("promise still pending")
		return PromiseResult{}
	}
}

// settledEnc is the generator's { value } / { error } encoding of a settled promise.
func settledEnc(t *testing.T, vm *QuickJS, r PromiseResult) obj {
	t.Helper()
	if r.Value != nil {
		defer r.Value.Dispose()
		return obj{"value": mustDumpEnc(t, vm, r.Value)}
	}
	defer r.Error.Dispose()
	return obj{"error": mustDumpEnc(t, vm, r.Error)}
}

func intPtr(v int) *int { return &v }

func uint32Ptr(v uint32) *uint32 { return &v }

func strOrNil(s *string) any {
	if s == nil {
		return nil
	}
	return encStr(*s)
}
