// Regenerates ../width_data.go (grok-mermaid@0.2.3 src/width-data.ts) and ../alnum_data.go (the
// code points matching `/[\p{Alphabetic}\p{N}]/u` in this Node's ICU, which labels.ts uses for
// Rust's `char::is_alphanumeric`).
// Usage (from this directory): node gen_tables.mjs <path to the pi TS checkout>
import {writeFileSync} from 'node:fs';
import {pathToFileURL} from 'node:url';
import path from 'node:path';

const root = path.resolve(process.argv[2] ?? '../../../../pi');
const {WIDTHS} = await import(pathToFileURL(path.join(root, 'node_modules/grok-mermaid/dist/width-data.js')).href);

const hex = (n) => `0x${n.toString(16)}`;
let go = '// Generated by testdata/gen_tables.mjs from grok-mermaid@0.2.3 src/width-data.ts. DO NOT EDIT.\n\npackage mermaid\n\n';
go += '// widths holds sorted, contiguous [lo, hi, width] runs covering the whole code point space: the\n';
go += '// width of that code point alone in a string, per the unicode-width crate.\n';
go += 'var widths = [][3]int32{\n';
for (const [lo, hi, w] of WIDTHS) go += `\t{${hex(lo)}, ${hex(hi)}, ${w}},\n`;
go += '}\n';
writeFileSync(new URL('../width_data.go', import.meta.url), go);

const re = /[\p{Alphabetic}\p{N}]/u;
const ranges = [];
for (let cp = 0; cp <= 0x10ffff; cp++) {
	if (cp >= 0xd800 && cp <= 0xdfff) continue;
	if (!re.test(String.fromCodePoint(cp))) continue;
	const last = ranges.at(-1);
	if (last && last[1] === cp - 1) last[1] = cp;
	else ranges.push([cp, cp]);
}
let alnum = `// Generated by testdata/gen_tables.mjs with Node ${process.version} (ICU ${process.versions.icu}, Unicode ${process.versions.unicode}). DO NOT EDIT.\n\npackage mermaid\n\n`;
alnum += '// alnumRanges are the inclusive code point ranges matching `/[\\p{Alphabetic}\\p{N}]/u`.\n';
alnum += 'var alnumRanges = [][2]rune{\n';
for (const [lo, hi] of ranges) alnum += `\t{${hex(lo)}, ${hex(hi)}},\n`;
alnum += '}\n';
writeFileSync(new URL('../alnum_data.go', import.meta.url), alnum);
