package lockfile

import (
	"context"
	"encoding/json"
	"errors"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"
	"testing/synctest"
	"time"

	"github.com/google/go-cmp/cmp"
)

// testdata/proper_lockfile_vectors.json was generated by running proper-lockfile@4.1.2 and its bundled
// retry@0.12.0 under node v24.21.0 (generator script: gen-lock.cjs, not kept). Temp dir paths are
// replaced by <DIR>.
type lockVectors struct {
	Timeouts []struct {
		Options  map[string]any `json:"options"`
		Timeouts []float64      `json:"timeouts"`
	} `json:"timeouts"`
	MinMaxError string `json:"minMaxError"`
	Errors      []struct {
		Name    string `json:"name"`
		OK      bool   `json:"ok"`
		Code    string `json:"code"`
		Message string `json:"message"`
		File    string `json:"file"`
		Syscall string `json:"syscall"`
		Path    string `json:"path"`
	} `json:"errors"`
}

func loadLockVectors(t *testing.T) *lockVectors {
	t.Helper()
	data, err := os.ReadFile("testdata/proper_lockfile_vectors.json")
	if err != nil {
		t.Fatal(err)
	}
	var v lockVectors
	if err := json.Unmarshal(data, &v); err != nil {
		t.Fatal(err)
	}
	return &v
}

func tempDir(t *testing.T) string {
	t.Helper()
	dir, err := filepath.EvalSymlinks(t.TempDir())
	if err != nil {
		t.Fatal(err)
	}
	return dir
}

func lockErr(t *testing.T, err error) *Error {
	t.Helper()
	var e *Error
	if !errors.As(err, &e) {
		t.Fatalf("error %v (%T) is not a *lockfile.Error", err, err)
	}
	return e
}

type errorList struct {
	mu   sync.Mutex
	errs []error
}

func (l *errorList) add(err error) {
	l.mu.Lock()
	defer l.mu.Unlock()
	l.errs = append(l.errs, err)
}

func (l *errorList) len() int {
	l.mu.Lock()
	defer l.mu.Unlock()
	return len(l.errs)
}

func (l *errorList) get(i int) error {
	l.mu.Lock()
	defer l.mu.Unlock()
	return l.errs[i]
}

func (l *errorList) all() []error {
	l.mu.Lock()
	defer l.mu.Unlock()
	return append([]error{}, l.errs...)
}

func touch(t *testing.T, path string) {
	t.Helper()
	if err := os.WriteFile(path, nil, 0o644); err != nil {
		t.Fatal(err)
	}
}

func TestLockfile_RetryTimeoutsMatchRetry(t *testing.T) {
	v := loadLockVectors(t)
	for _, c := range v.Timeouts {
		opts := &RetryOptions{}
		for key, value := range c.Options {
			switch key {
			case "retries":
				opts.Retries = new(int(value.(float64)))
			case "factor":
				opts.Factor = new(value.(float64))
			case "minTimeout":
				opts.MinTimeout = new(int64(value.(float64)))
			case "maxTimeout":
				opts.MaxTimeout = new(int64(value.(float64)))
			case "maxRetryTime":
				opts.MaxRetryTime = new(int64(value.(float64)))
			case "forever":
				opts.Forever = value.(bool)
			}
		}
		got, err := retryTimeouts(opts)
		if err != nil {
			t.Fatal(err)
		}
		if diff := cmp.Diff(c.Timeouts, got); diff != "" {
			t.Errorf("options %v (-want +got):\n%s", c.Options, diff)
		}
	}
	_, err := retryTimeouts(&RetryOptions{MinTimeout: new(int64(5)), MaxTimeout: new(int64(1))})
	if err == nil || err.Error() != v.MinMaxError {
		t.Errorf("min > max error = %v, want %q", err, v.MinMaxError)
	}
}

func TestLockfile_RetryOperationMainError(t *testing.T) {
	op, err := newRetryOperation(&RetryOptions{Retries: new(3), MinTimeout: new(int64(1))})
	if err != nil {
		t.Fatal(err)
	}
	op.attempt()
	a1 := &Error{Message: "a"}
	b1 := &Error{Message: "b"}
	a2 := &Error{Message: "a"}
	b2 := &Error{Message: "b"}
	for _, e := range []error{a1, b1, a2} {
		if retry, _ := op.retry(e); !retry {
			t.Fatal("expected retry")
		}
	}
	if retry, _ := op.retry(b2); retry {
		t.Fatal("expected retries exhausted")
	}
	// a and b both appear twice: ties go to the later error.
	if got := op.mainError(); got != b2 {
		t.Fatalf("mainError = %p, want b2 %p", got, b2)
	}

	timed, _ := newRetryOperation(&RetryOptions{Retries: new(3), MaxRetryTime: new(int64(1))})
	timed.attempt()
	timed.operationStart -= 10
	if retry, _ := timed.retry(a1); retry {
		t.Fatal("expected maxRetryTime to stop retries")
	}
	if got := timed.mainError(); got.Error() != "RetryOperation timeout occurred" {
		t.Fatalf("mainError = %v", got)
	}

	forever, _ := newRetryOperation(&RetryOptions{Retries: new(1), Forever: true, MinTimeout: new(int64(1))})
	forever.attempt()
	for i := 0; i < 5; i++ {
		if retry, delay := forever.retry(a1); !retry || delay != 1 {
			t.Fatalf("forever retry %d = %v %v", i, retry, delay)
		}
	}
}

func TestLockfile_ErrorsMatchProperLockfile(t *testing.T) {
	v := loadLockVectors(t)
	dir := tempDir(t)
	want := map[string]int{}
	for i, e := range v.Errors {
		want[e.Name] = i
	}
	check := func(name string, err error) {
		t.Helper()
		w := v.Errors[want[name]]
		if err == nil {
			t.Errorf("%s: no error, want %q", name, w.Message)
			return
		}
		msg := strings.ReplaceAll(err.Error(), dir, "<DIR>")
		if msg != w.Message {
			t.Errorf("%s: message %q, want %q", name, msg, w.Message)
		}
		var e *Error
		if errors.As(err, &e) {
			if e.Code != w.Code || strings.ReplaceAll(e.File, dir, "<DIR>") != w.File || e.Syscall != w.Syscall || strings.ReplaceAll(e.Path, dir, "<DIR>") != w.Path {
				t.Errorf("%s: got code=%q file=%q syscall=%q path=%q, want %+v", name, e.Code, e.File, e.Syscall, e.Path, w)
			}
		} else if w.Code != "" {
			t.Errorf("%s: %T has no code, want %q", name, err, w.Code)
		}
	}

	_, err := Lock(context.Background(), filepath.Join(dir, "missing"), nil)
	check("realpath-missing", err)
	_, err = Lock(context.Background(), filepath.Join(dir, "nope", "file"), &Options{Realpath: new(false)})
	check("mkdir-missing-parent", err)

	f := filepath.Join(dir, "f")
	touch(t, f)
	release, err := Lock(context.Background(), f, nil)
	if err != nil {
		t.Fatal(err)
	}
	_, err = Lock(context.Background(), f, nil)
	check("elocked", err)
	_, err = LockSync(f, &Options{Realpath: new(false)})
	check("elocked-sync", err)
	_, err = LockSync(f, &Options{Retries: Retries(1)})
	check("esync", err)
	_, err = LockSync(f, &Options{Retries: &RetryOptions{Retries: new(2)}})
	check("esync-object", err)
	g := filepath.Join(dir, "g")
	_, err = LockSync(g, &Options{Realpath: new(false), Retries: &RetryOptions{Retries: new(0), MinTimeout: new(int64(5)), MaxTimeout: new(int64(1))}})
	check("min-max-sync", err)
	_, err = Lock(context.Background(), g, &Options{Realpath: new(false), Retries: &RetryOptions{Retries: new(0), MinTimeout: new(int64(5)), MaxTimeout: new(int64(1))}})
	check("min-max-async", err)
	if err := release(); err != nil {
		t.Fatal(err)
	}
	check("ereleased", release())
	check("enotacquired", Unlock(f, nil))
	check("enotacquired-sync", UnlockSync(f, nil))

	h := filepath.Join(dir, "h")
	if err := os.WriteFile(h+".lock", []byte("not a dir"), 0o644); err != nil {
		t.Fatal(err)
	}
	_, err = Lock(context.Background(), h, &Options{Realpath: new(false), Stale: new(int64(2000))})
	check("lock-on-file-lockpath", err)
	old := time.Now().Add(-time.Minute)
	if err := os.Chtimes(h+".lock", old, old); err != nil {
		t.Fatal(err)
	}
	_, err = Lock(context.Background(), h, &Options{Realpath: new(false), Stale: new(int64(2000))})
	check("stale-file-lockpath", err)
	_, err = Check(filepath.Join(dir, "zzz"), nil)
	check("check-missing-realpath", err)
}

func TestLockfile_LockCreatesAndReleaseRemovesLockDir(t *testing.T) {
	dir := tempDir(t)
	file := filepath.Join(dir, "settings.json")
	release, err := LockSync(file, &Options{Realpath: new(false)})
	if err != nil {
		t.Fatal(err)
	}
	info, err := os.Stat(file + ".lock")
	if err != nil || !info.IsDir() {
		t.Fatalf("lock dir: %v %v", info, err)
	}
	locked, err := Check(file, &Options{Realpath: new(false)})
	if err != nil || !locked {
		t.Fatalf("Check = %v %v", locked, err)
	}
	if err := release(); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(file + ".lock"); !errors.Is(err, fs.ErrNotExist) {
		t.Fatalf("lock dir still present: %v", err)
	}
	locked, err = CheckSync(file, &Options{Realpath: new(false)})
	if err != nil || locked {
		t.Fatalf("Check after release = %v %v", locked, err)
	}
}

func TestLockfile_LockfilePathOption(t *testing.T) {
	dir := tempDir(t)
	trustDir := filepath.Join(dir, "trust")
	if err := os.Mkdir(trustDir, 0o755); err != nil {
		t.Fatal(err)
	}
	lockPath := filepath.Join(dir, "trust.json.lock")
	release, err := LockSync(trustDir, &Options{Realpath: new(false), LockfilePath: lockPath})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(lockPath); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(trustDir + ".lock"); !errors.Is(err, fs.ErrNotExist) {
		t.Fatalf("default lock path used: %v", err)
	}
	if _, err := LockSync(trustDir, &Options{Realpath: new(false), LockfilePath: lockPath}); lockErr(t, err).Code != "ELOCKED" {
		t.Fatalf("second lock: %v", err)
	}
	if err := Unlock(trustDir, &Options{Realpath: new(false), LockfilePath: lockPath}); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(lockPath); !errors.Is(err, fs.ErrNotExist) {
		t.Fatalf("lock not removed: %v", err)
	}
	if err := release(); lockErr(t, err).Code != "ERELEASED" {
		t.Fatalf("release after unlock: %v", err)
	}
}

func TestLockfile_StaleLockIsTakenOver(t *testing.T) {
	dir := tempDir(t)
	file := filepath.Join(dir, "auth.json")
	if err := os.Mkdir(file+".lock", 0o755); err != nil {
		t.Fatal(err)
	}
	if _, err := LockSync(file, &Options{Realpath: new(false)}); lockErr(t, err).Code != "ELOCKED" {
		t.Fatalf("fresh foreign lock: %v", err)
	}
	old := time.Now().Add(-11 * time.Second)
	if err := os.Chtimes(file+".lock", old, old); err != nil {
		t.Fatal(err)
	}
	if locked, _ := Check(file, &Options{Realpath: new(false)}); locked {
		t.Fatal("Check reports a stale lock as locked")
	}
	// A shorter stale threshold makes a 3s-old lock stale; the default keeps it.
	release, err := LockSync(file, &Options{Realpath: new(false)})
	if err != nil {
		t.Fatalf("stale lock not taken over: %v", err)
	}
	if err := release(); err != nil {
		t.Fatal(err)
	}
	if err := os.Mkdir(file+".lock", 0o755); err != nil {
		t.Fatal(err)
	}
	old = time.Now().Add(-3 * time.Second)
	if err := os.Chtimes(file+".lock", old, old); err != nil {
		t.Fatal(err)
	}
	if _, err := LockSync(file, &Options{Realpath: new(false)}); lockErr(t, err).Code != "ELOCKED" {
		t.Fatalf("3s-old lock with default stale: %v", err)
	}
	release, err = LockSync(file, &Options{Realpath: new(false), Stale: new(int64(0))}) // clamped to 2000
	if err != nil {
		t.Fatalf("3s-old lock with stale 2000: %v", err)
	}
	_ = release()
}

func TestLockfile_RealpathResolvesSymlinks(t *testing.T) {
	dir := tempDir(t)
	target := filepath.Join(dir, "target")
	touch(t, target)
	link := filepath.Join(dir, "link")
	if err := os.Symlink(target, link); err != nil {
		t.Skip("symlinks unavailable:", err)
	}
	release, err := Lock(context.Background(), link, nil)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(target + ".lock"); err != nil {
		t.Fatalf("lock not placed next to the real file: %v", err)
	}
	if _, err := Lock(context.Background(), target, nil); lockErr(t, err).Code != "ELOCKED" {
		t.Fatalf("lock through target: %v", err)
	}
	if err := Unlock(link, nil); err != nil {
		t.Fatalf("unlock through link: %v", err)
	}
	if err := release(); lockErr(t, err).Code != "ERELEASED" {
		t.Fatalf("release after unlock: %v", err)
	}
}

func TestLockfile_RelativePathIsResolved(t *testing.T) {
	dir := tempDir(t)
	t.Chdir(dir)
	release, err := LockSync("rel.json", &Options{Realpath: new(false)})
	if err != nil {
		t.Fatal(err)
	}
	if err := Unlock(filepath.Join(dir, "rel.json"), &Options{Realpath: new(false)}); err != nil {
		t.Fatalf("unlock by absolute path: %v", err)
	}
	if err := release(); lockErr(t, err).Code != "ERELEASED" {
		t.Fatalf("release: %v", err)
	}
}

func TestLockfile_RetriesWaitForRelease(t *testing.T) {
	dir := tempDir(t)
	file := filepath.Join(dir, "update")
	release, err := Lock(context.Background(), file, &Options{Realpath: new(false)})
	if err != nil {
		t.Fatal(err)
	}
	start := time.Now()
	_, err = Lock(context.Background(), file, &Options{Realpath: new(false), Retries: &RetryOptions{Retries: new(3), Factor: new(1.0), MinTimeout: new(int64(20)), MaxTimeout: new(int64(20))}})
	if lockErr(t, err).Code != "ELOCKED" {
		t.Fatalf("expected ELOCKED after retries: %v", err)
	}
	if elapsed := time.Since(start); elapsed < 60*time.Millisecond {
		t.Fatalf("retries finished after %v, want >= 60ms", elapsed)
	}

	var wg sync.WaitGroup
	wg.Go(func() {
		time.Sleep(50 * time.Millisecond)
		if err := release(); err != nil {
			t.Error(err)
		}
	})
	release2, err := Lock(context.Background(), file, &Options{Realpath: new(false), Retries: &RetryOptions{Retries: new(50), Factor: new(1.0), MinTimeout: new(int64(10))}})
	wg.Wait()
	if err != nil {
		t.Fatalf("lock after release: %v", err)
	}
	if err := release2(); err != nil {
		t.Fatal(err)
	}
}

func TestLockfile_ContextCancelsRetryWait(t *testing.T) {
	dir := tempDir(t)
	file := filepath.Join(dir, "x")
	release, err := LockSync(file, &Options{Realpath: new(false)})
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = release() }()
	ctx, cancel := context.WithCancelCause(context.Background())
	cause := errors.New("stop waiting")
	time.AfterFunc(30*time.Millisecond, func() { cancel(cause) })
	_, err = Lock(ctx, file, &Options{Realpath: new(false), Retries: &RetryOptions{Retries: new(100), Factor: new(1.0), MinTimeout: new(int64(1000))}})
	if !errors.Is(err, cause) {
		t.Fatalf("err = %v, want cancel cause", err)
	}
}

func TestLockfile_ProbeSetsFutureMtimeOnFirstAsyncLock(t *testing.T) {
	precisionMu.Lock()
	precisionCache = ""
	precisionMu.Unlock()
	dir := tempDir(t)
	file := filepath.Join(dir, "p")
	release, err := Lock(context.Background(), file, &Options{Realpath: new(false)})
	if err != nil {
		t.Fatal(err)
	}
	info, err := os.Stat(file + ".lock")
	if err != nil {
		t.Fatal(err)
	}
	if ms := info.ModTime().UnixMilli(); ms%1000 != 5 {
		t.Fatalf("probe mtime %d, want ceil(now)+5ms", ms)
	}
	precisionMu.Lock()
	cached := precisionCache
	precisionMu.Unlock()
	if cached != "ms" && cached != "s" {
		t.Fatalf("precision not cached: %q", cached)
	}
	_ = release()

	// Sync locks never use the shared cache: they probe every time.
	release, err = LockSync(file, &Options{Realpath: new(false)})
	if err != nil {
		t.Fatal(err)
	}
	info, _ = os.Stat(file + ".lock")
	if ms := info.ModTime().UnixMilli(); ms%1000 != 5 && cached == "ms" {
		t.Fatalf("sync probe mtime %d", ms)
	}
	_ = release()
}

func TestLockfile_UpdateKeepsLockFresh(t *testing.T) {
	dir := tempDir(t)
	synctest.Test(t, func(t *testing.T) {
		file := filepath.Join(dir, "fresh")
		var compromised errorList
		release, err := Lock(context.Background(), file, &Options{
			Realpath:      new(false),
			Stale:         new(int64(2000)),
			OnCompromised: compromised.add,
		})
		if err != nil {
			t.Fatal(err)
		}
		for i := 0; i < 6; i++ {
			time.Sleep(1000 * time.Millisecond)
			synctest.Wait()
			locked, err := Check(file, &Options{Realpath: new(false), Stale: new(int64(2000))})
			if err != nil || !locked {
				t.Fatalf("after %ds: locked=%v err=%v", i+1, locked, err)
			}
		}
		info, _ := os.Stat(file + ".lock")
		if now := time.Now().UnixMilli(); now-info.ModTime().UnixMilli() > 1000 {
			t.Fatalf("mtime %d not refreshed (now %d)", info.ModTime().UnixMilli(), now)
		}
		if err := release(); err != nil {
			t.Fatal(err)
		}
		time.Sleep(5 * time.Second)
		synctest.Wait()
		if compromised.len() != 0 {
			t.Fatalf("compromised: %v", compromised.all())
		}
	})
}

func TestLockfile_CompromisedWhenLockDirRemoved(t *testing.T) {
	dir := tempDir(t)
	synctest.Test(t, func(t *testing.T) {
		file := filepath.Join(dir, "removed")
		var compromised errorList
		release, err := Lock(context.Background(), file, &Options{
			Realpath:      new(false),
			OnCompromised: compromised.add,
		})
		if err != nil {
			t.Fatal(err)
		}
		if err := os.Remove(file + ".lock"); err != nil {
			t.Fatal(err)
		}
		time.Sleep(5001 * time.Millisecond)
		synctest.Wait()
		if compromised.len() != 1 {
			t.Fatalf("compromised = %v", compromised.all())
		}
		e := lockErr(t, compromised.get(0))
		if e.Code != "ECOMPROMISED" || e.Message != "ENOENT: no such file or directory, stat '"+file+".lock'" {
			t.Fatalf("compromised error = %+v", e)
		}
		if err := release(); lockErr(t, err).Code != "ERELEASED" {
			t.Fatalf("release after compromise: %v", err)
		}
		// The compromised lock no longer blocks a new one.
		release2, err := Lock(context.Background(), file, &Options{Realpath: new(false), OnCompromised: func(error) {}})
		if err != nil {
			t.Fatal(err)
		}
		_ = release2()
	})
}

func TestLockfile_CompromisedWhenMtimeChanged(t *testing.T) {
	dir := tempDir(t)
	synctest.Test(t, func(t *testing.T) {
		file := filepath.Join(dir, "stolen")
		var compromised errorList
		_, err := Lock(context.Background(), file, &Options{
			Realpath:      new(false),
			Stale:         new(int64(4000)),
			OnCompromised: compromised.add,
		})
		if err != nil {
			t.Fatal(err)
		}
		other := time.Now().Add(-500 * time.Millisecond)
		if err := os.Chtimes(file+".lock", other, other); err != nil {
			t.Fatal(err)
		}
		time.Sleep(2001 * time.Millisecond)
		synctest.Wait()
		if compromised.len() != 1 {
			t.Fatalf("compromised = %v", compromised.all())
		}
		e := lockErr(t, compromised.get(0))
		if e.Code != "ECOMPROMISED" || e.Message != "Unable to update lock within the stale threshold" {
			t.Fatalf("compromised error = %+v", e)
		}
		if err := os.Remove(file + ".lock"); err != nil {
			t.Fatal(err)
		}
	})
}

func TestLockfile_DefaultOnCompromisedPanics(t *testing.T) {
	o := resolveLockOptions(nil, false)
	want := &Error{Code: "ECOMPROMISED", Message: "x"}
	defer func() {
		if r := recover(); r != want {
			t.Fatalf("recover() = %v", r)
		}
	}()
	o.onCompromised(want)
}

func TestLockfile_OptionDefaults(t *testing.T) {
	cases := []struct {
		name          string
		options       *Options
		stale, update float64
	}{
		{"defaults", nil, 10000, 5000},
		{"stale 0 clamps to 2000", &Options{Stale: new(int64(0))}, 2000, 1000},
		{"update 0 clamps to 1000", &Options{Update: new(int64(0))}, 10000, 1000},
		{"update above stale/2", &Options{Stale: new(int64(30000)), Update: new(int64(20000))}, 30000, 15000},
		{"update below 1000", &Options{Stale: new(int64(30000)), Update: new(int64(10))}, 30000, 1000},
		{"server launcher", &Options{Stale: new(int64(10000)), Update: new(int64(10000 / 3))}, 10000, 3333},
	}
	for _, c := range cases {
		o := resolveLockOptions(c.options, false)
		if o.stale != c.stale || o.update != c.update || !o.realpath {
			t.Errorf("%s: stale=%v update=%v realpath=%v", c.name, o.stale, o.update, o.realpath)
		}
	}
}

func TestLockfile_CleanupOnExitRemovesHeldLocks(t *testing.T) {
	dir := tempDir(t)
	a := filepath.Join(dir, "a")
	b := filepath.Join(dir, "b")
	releaseA, err := LockSync(a, &Options{Realpath: new(false)})
	if err != nil {
		t.Fatal(err)
	}
	releaseB, err := Lock(context.Background(), b, &Options{Realpath: new(false)})
	if err != nil {
		t.Fatal(err)
	}
	CleanupOnExit()
	for _, p := range []string{a + ".lock", b + ".lock"} {
		if _, err := os.Stat(p); !errors.Is(err, fs.ErrNotExist) {
			t.Fatalf("%s still present: %v", p, err)
		}
	}
	// Releasing afterwards ignores the missing directories, as rmdir ENOENT is ignored.
	if err := releaseA(); err != nil {
		t.Fatal(err)
	}
	if err := releaseB(); err != nil {
		t.Fatal(err)
	}
}

func TestLockfile_ConcurrentLockersExcludeEachOther(t *testing.T) {
	dir := tempDir(t)
	file := filepath.Join(dir, "shared")
	var mu sync.Mutex
	holders, maxHolders := 0, 0
	var wg sync.WaitGroup
	for i := 0; i < 8; i++ {
		wg.Go(func() {
			release, err := Lock(context.Background(), file, &Options{Realpath: new(false), Retries: &RetryOptions{Retries: new(500), Factor: new(1.0), MinTimeout: new(int64(2))}})
			if err != nil {
				t.Error(err)
				return
			}
			mu.Lock()
			holders++
			maxHolders = max(maxHolders, holders)
			mu.Unlock()
			time.Sleep(5 * time.Millisecond)
			mu.Lock()
			holders--
			mu.Unlock()
			if err := release(); err != nil {
				t.Error(err)
			}
		})
	}
	wg.Wait()
	if maxHolders != 1 {
		t.Fatalf("max concurrent holders = %d", maxHolders)
	}
}
