// Regenerates ../lookup_data.go and vectors.json from get-east-asian-width@1.6.0.
// Usage (from this directory): node gen.mjs <path to the pi TS checkout>
import {writeFileSync} from 'node:fs';
import {pathToFileURL} from 'node:url';
import path from 'node:path';

const root = path.resolve(process.argv[2] ?? '../../../../pi');
const pkg = path.join(root, 'node_modules/get-east-asian-width');
const data = await import(pathToFileURL(path.join(pkg, 'lookup-data.js')).href);
const api = await import(pathToFileURL(path.join(pkg, 'index.js')).href);

const kinds = ['ambiguous', 'fullwidth', 'halfwidth', 'narrow', 'wide'];
let go = '// Generated by testdata/gen.mjs from get-east-asian-width@1.6.0 lookup-data.js. DO NOT EDIT.\n\npackage eastasian\n';
for (const k of kinds) {
	const ranges = data[`${k}Ranges`];
	go += `\nconst (\n\t${k}MinimalCodePoint = ${data[`${k}MinimalCodePoint`]}\n\t${k}MaximumCodePoint = ${data[`${k}MaximumCodePoint`]}\n)\n`;
	go += `\n// ${k}Ranges is a flat list of inclusive [start, end] pairs.\nvar ${k}Ranges = []rune{\n`;
	for (let i = 0; i < ranges.length; i += 8) {
		go += '\t' + ranges.slice(i, i + 8).map((n) => `0x${n.toString(16).toUpperCase()}`).join(', ') + ',\n';
	}
	go += '}\n';
}
writeFileSync(new URL('../lookup_data.go', import.meta.url), go);

// Run-length vectors over the whole code point space plus a margin past it:
// each run is [start, type, width, widthAmbiguousAsWide].
const runs = [];
let prev = '';
for (let cp = 0; cp <= 0x110010; cp++) {
	const t = api.eastAsianWidthType(cp);
	const w = api.eastAsianWidth(cp);
	const wa = api.eastAsianWidth(cp, {ambiguousAsWide: true});
	const key = `${t}/${w}/${wa}`;
	if (key !== prev) {
		runs.push([cp, t, w, wa]);
		prev = key;
	}
}
const extra = [-1, 0x7fffffff].map((cp) => [cp, api.eastAsianWidthType(cp), api.eastAsianWidth(cp), api.eastAsianWidth(cp, {ambiguousAsWide: true})]);
writeFileSync(new URL('vectors.json', import.meta.url), JSON.stringify({node: process.version, end: 0x110010, runs, extra}) + '\n');
