// Package core is the Go port of these pi v1.0.0 TypeScript files
// (authoritative mapping: porting/filemap.tsv):
//
//   - packages/coding-agent/src/cli/args.ts -> args.go
//   - packages/coding-agent/src/core/agent-session-runtime.ts -> agent_session_runtime.go
//   - packages/coding-agent/src/core/agent-session-services.ts -> agent_session_services.go
//   - packages/coding-agent/src/core/agent-session.ts#L1-L1385 -> agent_session_part1.go
//   - packages/coding-agent/src/core/agent-session.ts#L1386-L2666 -> agent_session_part2.go
//   - packages/coding-agent/src/core/agent-session.ts#L2667-L4348 -> agent_session_part3.go
//   - packages/coding-agent/src/core/auth-guidance.ts -> auth_guidance.go
//   - packages/coding-agent/src/core/auth-storage.ts -> auth_storage.go
//   - packages/coding-agent/src/core/bash-executor.ts -> bash_executor.go
//   - packages/coding-agent/src/core/bug-report-upload.ts -> bug_report_upload.go
//   - packages/coding-agent/src/core/bug-report.ts -> bug_report.go
//   - packages/coding-agent/src/core/cache-stats.ts -> cache_stats.go
//   - packages/coding-agent/src/core/cache-warmer.ts -> cache_warmer.go
//   - packages/coding-agent/src/core/compaction/branch-summarization.ts -> compaction_branch_summarization.go
//   - packages/coding-agent/src/core/compaction/compaction.ts -> compaction_compaction.go
//   - packages/coding-agent/src/core/compaction/utils.ts -> compaction_utils.go
//   - packages/coding-agent/src/core/crash-log.ts -> crash_log.go
//   - packages/coding-agent/src/core/defaults.ts -> defaults.go
//   - packages/coding-agent/src/core/diagnostics.ts -> diagnostics.go
//   - packages/coding-agent/src/core/event-bus.ts -> event_bus.go
//   - packages/coding-agent/src/core/exec.ts -> exec.go
//   - packages/coding-agent/src/core/experimental.ts -> experimental.go
//   - packages/coding-agent/src/core/export-html/ansi-to-html.ts -> export_html_ansi_to_html.go
//   - packages/coding-agent/src/core/export-html/index.ts -> export_html_index.go
//   - packages/coding-agent/src/core/export-html/tool-renderer.ts -> export_html_tool_renderer.go
//   - packages/coding-agent/src/core/extensions/loader.ts -> extensions_loader.go
//   - packages/coding-agent/src/core/extensions/runner.ts -> extensions_runner.go
//   - packages/coding-agent/src/core/extensions/types.ts -> extensions_types.go
//   - packages/coding-agent/src/core/extensions/wrapper.ts -> extensions_wrapper.go
//   - packages/coding-agent/src/core/footer-data-provider.ts -> footer_data_provider.go
//   - packages/coding-agent/src/core/http-dispatcher.ts -> http_dispatcher.go
//   - packages/coding-agent/src/core/keybindings.ts -> keybindings.go
//   - packages/coding-agent/src/core/mcp-servers.ts -> mcp_servers.go
//   - packages/coding-agent/src/core/messages.ts -> messages.go
//   - packages/coding-agent/src/core/model-config.ts -> model_config.go
//   - packages/coding-agent/src/core/model-registry.ts -> model_registry.go
//   - packages/coding-agent/src/core/model-resolver.ts -> model_resolver.go
//   - packages/coding-agent/src/core/model-runtime.ts -> model_runtime.go
//   - packages/coding-agent/src/core/models-store.ts -> models_store.go
//   - packages/coding-agent/src/core/nested-tool-calls.ts -> nested_tool_calls.go
//   - packages/coding-agent/src/core/output-guard.ts -> output_guard.go
//   - packages/coding-agent/src/core/package-manager.ts -> package_manager.go
//   - packages/coding-agent/src/core/pi-manifest.ts -> pi_manifest.go
//   - packages/coding-agent/src/core/project-trust.ts -> project_trust.go
//   - packages/coding-agent/src/core/prompt-templates.ts -> prompt_templates.go
//   - packages/coding-agent/src/core/provider-attribution.ts -> provider_attribution.go
//   - packages/coding-agent/src/core/provider-composer.ts -> provider_composer.go
//   - packages/coding-agent/src/core/radius.ts -> radius.go
//   - packages/coding-agent/src/core/remote-catalog-provider.ts -> remote_catalog_provider.go
//   - packages/coding-agent/src/core/resolve-config-value.ts -> resolve_config_value.go
//   - packages/coding-agent/src/core/resource-loader.ts -> resource_loader.go
//   - packages/coding-agent/src/core/runtime-credentials.ts -> runtime_credentials.go
//   - packages/coding-agent/src/core/sdk.ts -> sdk.go
//   - packages/coding-agent/src/core/session-cwd.ts -> session_cwd.go
//   - packages/coding-agent/src/core/session-export.ts -> session_export.go
//   - packages/coding-agent/src/core/session-manager.ts -> session_manager.go
//   - packages/coding-agent/src/core/settings-diagnostics.ts -> settings_diagnostics.go
//   - packages/coding-agent/src/core/settings-manager.ts -> settings_manager.go
//   - packages/coding-agent/src/core/skills.ts -> skills.go
//   - packages/coding-agent/src/core/slash-commands.ts -> slash_commands.go
//   - packages/coding-agent/src/core/system-prompt.ts -> system_prompt.go
//   - packages/coding-agent/src/core/telemetry.ts -> telemetry.go
//   - packages/coding-agent/src/core/timings.ts -> timings.go
//   - packages/coding-agent/src/core/tools/bash.ts -> tools_bash.go
//   - packages/coding-agent/src/core/tools/edit-diff.ts -> tools_edit_diff.go
//   - packages/coding-agent/src/core/tools/edit.ts -> tools_edit.go
//   - packages/coding-agent/src/core/tools/file-mutation-queue.ts -> tools_file_mutation_queue.go
//   - packages/coding-agent/src/core/tools/find.ts -> tools_find.go
//   - packages/coding-agent/src/core/tools/grep.ts -> tools_grep.go
//   - packages/coding-agent/src/core/tools/index.ts -> tools_index.go
//   - packages/coding-agent/src/core/tools/ls.ts -> tools_ls.go
//   - packages/coding-agent/src/core/tools/output-accumulator.ts -> tools_output_accumulator.go
//   - packages/coding-agent/src/core/tools/path-utils.ts -> tools_path_utils.go
//   - packages/coding-agent/src/core/tools/powershell.ts -> tools_powershell.go
//   - packages/coding-agent/src/core/tools/read.ts -> tools_read.go
//   - packages/coding-agent/src/core/tools/render-utils.ts -> tools_render_utils.go
//   - packages/coding-agent/src/core/tools/renderers/bash.ts -> tools_renderers_bash.go
//   - packages/coding-agent/src/core/tools/renderers/edit.ts -> tools_renderers_edit.go
//   - packages/coding-agent/src/core/tools/renderers/find.ts -> tools_renderers_find.go
//   - packages/coding-agent/src/core/tools/renderers/grep.ts -> tools_renderers_grep.go
//   - packages/coding-agent/src/core/tools/renderers/index.ts -> tools_renderers_index.go
//   - packages/coding-agent/src/core/tools/renderers/ls.ts -> tools_renderers_ls.go
//   - packages/coding-agent/src/core/tools/renderers/read.ts -> tools_renderers_read.go
//   - packages/coding-agent/src/core/tools/renderers/write.ts -> tools_renderers_write.go
//   - packages/coding-agent/src/core/tools/tool-definition-wrapper.ts -> tools_tool_definition_wrapper.go
//   - packages/coding-agent/src/core/tools/truncate.ts -> tools_truncate.go
//   - packages/coding-agent/src/core/tools/write.ts -> tools_write.go
//   - packages/coding-agent/src/core/trust-manager.ts -> trust_manager.go
//   - packages/coding-agent/src/core/usage-totals.ts -> usage_totals.go
//   - packages/coding-agent/src/core/virtual-models.ts -> virtual_models.go
//   - packages/coding-agent/src/modes/interactive/theme/theme-controller.ts -> theme_controller.go
package core
